# Generated by Django 5.1.5 on 2025-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='musics/', verbose_name='Загрузите музыку'),
        ),
    ]
